name: Build Docker Image
on:
  push:
    branches:
      - cicd-github-action
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      environment: release
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t abdulrahmanelfeki/bakehouse:v${{ github.run_number }}
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKER_USERNAME}}/bakehouse:v${{ github.run_number }}

    
