name: Build Docker Image
on:
  push:
    branches:
      - cicd-github-action
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      environment: release
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t abdulrahmanelfeki/bakehouse:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
        - name: push the docker image
          id: push-docker-image
          run: | 
            docker push ${{secrets.DOCKER_USERNAME}}/bakehouse:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
            echo "${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"  > ../build_num.txt
    
    deploy:
      name: deploy to local k8s cluster
      needs: build
      runs-on: ubuntu-latest
      environment: prod
      steps:
        - uses: actions/checkout@v2
        - name: deploy to k8s cluster
          run: |  
            export BUILD_NUMBER=$(cat ../build_num.txt)
            mv Deployment/deploy.yaml Deployment/deploy.yaml.tmp
            cat Deployment/deploy.yaml.tmp | envsubst > Deployment/deploy.yaml
            rm -rf Deployment/deploy.yaml.tmp
            kubectl apply -f Deployment --kubeconfig ${{ secrets.KUBECONFIG }} -n prod
      
    
  

    
